name: DevOps Pipeline

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
    types: [ open, synchromize, reopened ]

jobs:
  code_scanning:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: javascript, csharp
    - name: Autobuild
      uses: github/codeql-action/autobuild@v3
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
  
  
  
  
#  pushtoregistry:
#    runs-on: ubuntu-latest
#    steps:
#      - name: login to GitHub Container Registry
#        uses: docker/login-action@v2
#        with:
#          registry: ghcr.io
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#      - uses: actions/checkout@v3
#      - name: create image from repository
#        run: docker build -t ghcr.io/${{ github.actor }}/project .
#      - name: push image to GitHub Container Registry
#        run: docker push ghcr.io/${{ github.actor }}/project:latest
